---
title: "Step 9 - The multivariate CAR model"
description: "We explore extensions of the univariate CAR model described in Hierarchical Modeling and Analysis for Spatial data."
author:
  - name: Matthew Shisler
    affiliation: North Carloina State University - Department of Statistics
    affiliation-url: https://statistics.sciences.ncsu.edu/ 
categories: [Bayesian, MCMC, Spatial, CAR] # self-defined categories
draft: false 
format:
  html: 
    code-fold: true
execute: 
  cache: false
  freeze: auto
---


```{r}
#| label: load-packages
#| output: false
#| code-summary: "Code: Load the packages"

library(tidyverse)
library(igraph)
library(viridis)
```

## Intro

Here we will extend the univariate CAR model to the multivariate case. 

Consider a spatial domain $\mathcal{D} \in \mathbb{R}^2$ that is partitioned into $n$ areal units. In the univariate case we specified a spatial random effect $\boldsymbol\phi = (\phi_1,\dots,\phi_n)$ meant to capture the spatial dependence. In the multivariate case we specify a spatial random vector $\boldsymbol\phi^T = (\boldsymbol\phi_1, \boldsymbol\phi_2,\dots,\boldsymbol\phi_3)$ where each $\boldsymbol\phi_i = (\phi_{i1}, \phi_{i2},\dots, \phi_{ip})$ is $p \times 1$.

The joint distribution of $\boldsymbol\phi_i$ is derived from the full conditional distributions.
Under the Markov Random Field (MRF) assumption, the conditional distributions can be specified as
$$
p(\boldsymbol\phi_i|\boldsymbol\phi_{j\ne i}, \Gamma_i) = N\left(\sum_{i \sim j} \mathbf{B}_{ij}\boldsymbol\phi_j, \Gamma_i\right), \quad i,j = 1,\dots,n.
$$

where $\Gamma_i$ and $\mathbf{B}_{ij}$ are $p \times p$ matrices.

Recall the role of $\Gamma_i$ and $\mathbf{B}_{ij}$ are analogous to the roles of $\tau_i^2$ and $b_{ij}$, respectively, in the univariate CAR models. The matrix $\Gamma_i$ is the with-in unit covariance matrix which describes the dependence of the variables in the vector $\boldsymbophi_i$. The matrix $\mathbf{B}_{ij}$ is the matrix that allows us to weight the neighboring observations of location $i$ that are conditioned on in the full conditional. A convenient special case is to set $\mathbf{B}_{ij} = b_{ij}\mathbf{I}_p$ where $b_{ij} = w_{ij}/w_{i+}$. Recall, for a neighborhood matrix $\mathbf{W} = \{w_ij\}$,
$$
w_{ij} = 
\begin{cases}
1 \quad \text{if} \quad j \in \mathcal{N}(i),\\
0 \quad \text{otherwise}.
\end{cases}
$$
and $w_{i+} = \sum_{j=1}^pw_{ij}$, i.e. the number of neighbors of location $i$, $|\mathcal{N}(i)|$.


Specifying the conditional distributions in this way implies the unique joint distribution, via Brook's Lemma, to be
$$
p(\boldsymbol\phi \;| \;\{\Gamma_i\}) \propto \exp\left\{-\frac{1}{2}\boldsymbol\phi^T\Gamma^{-1}(\mathbf{I} - \tilde{\mathbf{B}})\phi\right\}
$$
where $\Gamma$ is block-diagonal with block $\Gamma_i$, and $\tilde{\mathbf{B}}$ is $np \times np$ with the $(i,j)$-th block $\mathbf{B}_{ij}$.







